type constantType = { [key: string]: string };

export const CONSTANTS: constantType = {
    DUPLICATION: "ALREADY EXISTS",
    INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
    USER_NOT_FOUND: "User with this email not found . please sign up",
    EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
    EMAIL_VERIFIED: "EMAIL_VERIFIED",
    SUCCESS: "SUCCESS",
    UNSUCCESS: "UNSUCCESS",
    EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
    ACCESS_TOKEN_MISSING: "ACCESS_TOKEN_MISSING",
    INVALID_REQUEST: "INVALID_REQUEST",
    FRIEND_REQUEST_ACCEPTED: "FRIEND_REQUEST_ACCEPTED",
    FRIEND_REQUEST_DECLINED: "FRIEND_REQUEST_DECLINED",
    RECIPIENT_NOT_EXISTS: "RECIPIENT_NOT_EXISTS",
    ALREADY_FRIENDS: "ALREADY_FRIENDS",
    REFRESH_TOKEN_DOESNOT_EXIST:"PLEASE LOGIN AGAIN",
};
